FROM apache/airflow:2.7.1

USER root

# Installation de Java
RUN apt-get update && \
    apt-get install -y --no-install-recommends openjdk-11-jre-headless wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Installation des binaires Spark 3.5.0 SPECIFIQUES pour Scala 2.13
ENV SPARK_VERSION=3.5.0
RUN wget --no-verbose https://archive.apache.org/dist/spark/spark-3.5.0/spark-3.5.0-bin-hadoop3-scala2.13.tgz && \
    tar -xzf spark-3.5.0-bin-hadoop3-scala2.13.tgz -C /opt && \
    mv /opt/spark-3.5.0-bin-hadoop3-scala2.13 /opt/spark && \
    rm spark-3.5.0-bin-hadoop3-scala2.13.tgz

# Ajout de Spark au PATH
ENV SPARK_HOME=/opt/spark
ENV PATH="${PATH}:${SPARK_HOME}/bin"

USER airflow
# Installation complète des dépendances
RUN pip install --no-cache-dir \
    "numpy<2.0.0" \
    scikit-learn \
    pandas \
    joblib \
    sqlalchemy \
    psycopg2-binary \
    tqdm \
    matplotlib \
    seaborn \
    flake8 \
    pyment \
    pytest \
    s3fs \
    streamlit
