
INSERT INTO Borough (name) VALUES
                               ('Manhattan'),
                               ('Brooklyn'),
                               ('Queens'),
                               ('Bronx'),
                               ('Staten Island'),
                               ('Unknown'),
                               ( 'EWR');

INSERT INTO Vendor (vendor_id, name) VALUES
                                         (1, 'Creative Mobile Technologies'),
                                         (2, 'VeriFone'),
                                         (6, 'Myle Technologies Inc'),
                                         (7, 'Helix'),
                                         (99, 'Unknown');

INSERT INTO Payment_Type (payment_type_id, description) VALUES
                                                            (0, 'Flex Fare'),
                                                            (1, 'Credit Card'),
                                                            (2, 'Cash'),
                                                            (3, 'No Charge'),
                                                            (4, 'Dispute'),
                                                            (5, 'Unknown'),
                                                            (6, 'Voided Trip');


-- Rate_Code (Codes tarifaires)

INSERT INTO Rate_Code (rate_code_id, description) VALUES
                                                      (1, 'Standard rate'),
                                                      (2, 'JFK'),
                                                      (3, 'Newark'),
                                                      (4, 'Nassau or Westchester'),
                                                      (5, 'Negotiated fare'),
                                                      (6, 'Group ride'),
                                                      (99, 'Unknown');




INSERT INTO Taxi_Zone (zone_id, name, borough_id) VALUES
                                                      (1, 'EWR', 7),
                                                      (2, 'Jamaica Bay', 3),
                                                      (3, 'Allerton/Pelham Gardens', 4),
                                                      (4, 'Alphabet City', 1),
                                                      (5, 'Arden Heights', 5),
                                                      (6, 'Arrochar/Fort Wadsworth', 5),
                                                      (7, 'Astoria', 3),
                                                      (8, 'Astoria Park', 3),
                                                      (9, 'Auburndale', 3),
                                                      (10, 'Baisley Park', 3),
                                                      (11, 'Bath Beach', 2),
                                                      (12, 'Battery Park', 1),
                                                      (13, 'Battery Park City', 1),
                                                      (14, 'Bay Ridge', 2),
                                                      (15, 'Bay Terrace/Fort Totten', 3),
                                                      (16, 'Bayside', 3),
                                                      (17, 'Bedford', 2),
                                                      (18, 'Bedford Park', 4),
                                                      (19, 'Bellerose', 3),
                                                      (20, 'Belmont', 4),
                                                      (21, 'Bensonhurst East', 2),
                                                      (22, 'Bensonhurst West', 2),
                                                      (23, 'Bloomfield/Emerson Hill', 5),
                                                      (24, 'Bloomingdale', 1),
                                                      (25, 'Boerum Hill', 2),
                                                      (26, 'Borough Park', 2),
                                                      (27, 'Breezy Point/Fort Tilden/Riis Park', 3),
                                                      (28, 'Briarwood/Jamaica Hills', 3),
                                                      (29, 'Brighton Beach', 2),
                                                      (30, 'Broad Channel', 3),
                                                      (31, 'Bronx Park', 4),
                                                      (32, 'Bronxdale', 4),
                                                      (33, 'Brooklyn Heights', 2),
                                                      (34, 'Brooklyn Navy Yard', 2),
                                                      (35, 'Brownsville', 2),
                                                      (36, 'Bushwick North', 2),
                                                      (37, 'Bushwick South', 2),
                                                      (38, 'Cambria Heights', 3),
                                                      (39, 'Canarsie', 2),
                                                      (40, 'Carroll Gardens', 2),
                                                      (41, 'Central Harlem', 1),
                                                      (42, 'Central Harlem North', 1),
                                                      (43, 'Central Park', 1),
                                                      (44, 'Charleston/Tottenville', 5),
                                                      (45, 'Chinatown', 1),
                                                      (46, 'City Island', 4),
                                                      (47, 'Claremont/Bathgate', 4),
                                                      (48, 'Clinton East', 1),
                                                      (49, 'Clinton Hill', 2),
                                                      (50, 'Clinton West', 1),
                                                      (51, 'Co-Op City', 4),
                                                      (52, 'Cobble Hill', 2),
                                                      (53, 'College Point', 3),
                                                      (54, 'Columbia Street', 2),
                                                      (55, 'Coney Island', 2),
                                                      (56, 'Corona', 3),
                                                      (57, 'Corona', 3),
                                                      (58, 'Cuylerville', 2),
                                                      (59, 'Ditmars Steinway', 3),
                                                      (60, 'Douglas Manor', 3),
                                                      (61, 'Downtown Brooklyn/MetroTech', 2),
                                                      (62, 'DUMBO/Vinegar Hill', 2),
                                                      (63, 'Dyker Heights', 2),
                                                      (64, 'East Concourse', 4),
                                                      (65, 'East Elmhurst', 3),
                                                      (66, 'East Harlem North', 1),
                                                      (67, 'East Harlem South', 1),
                                                      (68, 'East Chelsea', 1),
                                                      (69, 'East New York', 2),
                                                      (70, 'East New York/Pennsylvania Avenue', 2),
                                                      (71, 'East Tremont', 4),
                                                      (72, 'East Williamsburg', 2),
                                                      (73, 'Eastchester', 4),
                                                      (74, 'East Village', 1),
                                                      (75, 'East Williamsburg', 2),
                                                      (76, 'Eastchester', 4),
                                                      (77, 'East Village', 1),
                                                      (78, 'East Williamsburg', 2),
                                                      (79, 'East Village', 1),
                                                      (80, 'East Williamsburg', 2),
                                                      (81, 'Eastchester', 4),
                                                      (82, 'Elmhurst', 3),
                                                      (83, 'Elmhurst/Maspeth', 3),
                                                      (84, 'Eltingville/Annadale/Prince''s Bay', 5),
                                                      (85, 'Erasmus', 2),
                                                      (86, 'Far Rockaway', 3),
                                                      (87, 'Financial District North', 1),
                                                      (88, 'Financial District South', 1),
                                                      (89, 'Flatbush/Ditmas Park', 2),
                                                      (90, 'Flatiron', 1),
                                                      (91, 'Flatlands', 2),
                                                      (92, 'Flushing', 3),
                                                      (93, 'Flushing Meadows-Corona Park', 3),
                                                      (94, 'Forest Hills', 3),
                                                      (95, 'Forest Park', 3),
                                                      (96, 'Fort Greene', 2),
                                                      (97, 'Fort George', 1),
                                                      (98, 'Fresh Meadows', 3),
                                                      (99, 'Freshkills Park', 5),
                                                      (100, 'Garment District', 1),
                                                      (101, 'Glen Oaks', 3),
                                                      (102, 'Glendale', 3),
                                                      (103, 'Governors Island/Ellis Island/Liberty Island', 1),
                                                      (104, 'Governors Island/Ellis Island/Liberty Island', 1),
                                                      (105, 'Governors Island/Ellis Island/Liberty Island', 1),
                                                      (106, 'Gowanus', 2),
                                                      (107, 'Gramercy', 1),
                                                      (108, 'Grasmere/Concord', 5),
                                                      (109, 'Gravesend', 2),
                                                      (110, 'Great Kills', 5),
                                                      (111, 'Green-Wood Cemetery', 2),
                                                      (112, 'Greenpoint', 2),
                                                      (113, 'Greenwich Village North', 1),
                                                      (114, 'Greenwich Village South', 1),
                                                      (115, 'Grymes Hill/Clifton', 5),
                                                      (116, 'Hamilton Heights', 1),
                                                      (117, 'Hammels/Arverne', 3),
                                                      (118, 'Heartland Village/Todt Hill', 5),
                                                      (119, 'Highbridge', 4),
                                                      (120, 'Highbridge Park', 1),
                                                      (121, 'Hillcrest/Pomonok', 3),
                                                      (122, 'Hollis', 3),
                                                      (123, 'Homecrest', 2),
                                                      (124, 'Howard Beach', 3),
                                                      (125, 'Hudson Yards', 1),
                                                      (126, 'Hunts Point', 4),
                                                      (127, 'Inwood', 1),
                                                      (128, 'Inwood Hill Park', 1),
                                                      (129, 'Jackson Heights', 3),
                                                      (130, 'Jamaica', 3),
                                                      (131, 'Jamaica Estates', 3),
                                                      (132, 'JFK Airport', 3),
                                                      (133, 'Kensington', 2),
                                                      (134, 'Kew Gardens', 3),
                                                      (135, 'Kew Gardens Hills', 3),
                                                      (136, 'Kingsbridge Heights', 4),
                                                      (137, 'Kips Bay', 1),
                                                      (138, 'LaGuardia Airport', 3),
                                                      (139, 'Laurelton', 3),
                                                      (140, 'Lenox Hill East', 1),
                                                      (141, 'Lenox Hill West', 1),
                                                      (142, 'Lincoln Square East', 1),
                                                      (143, 'Lincoln Square West', 1),
                                                      (144, 'Little Italy/NoLiTa', 1),
                                                      (145, 'Long Island City/Hunters Point', 3),
                                                      (146, 'Long Island City/Queens Plaza', 3),
                                                      (147, 'Longwood', 4),
                                                      (148, 'Lower East Side', 1),
                                                      (149, 'Madison', 2),
                                                      (150, 'Manhattan Beach', 2),
                                                      (151, 'Manhattan Valley', 1),
                                                      (152, 'Manhattanville', 1),
                                                      (153, 'Marble Hill', 1),
                                                      (154, 'Marine Park/Floyd Bennett Field', 2),
                                                      (155, 'Marine Park/Mill Basin', 2),
                                                      (156, 'Mariners Harbor', 5),
                                                      (157, 'Maspeth', 3),
                                                      (158, 'Meatpacking/West Village West', 1),
                                                      (159, 'Melrose South', 4),
                                                      (160, 'Middle Village', 3),
                                                      (161, 'Midtown Center', 1),
                                                      (162, 'Midtown East', 1),
                                                      (163, 'Midtown North', 1),
                                                      (164, 'Midtown South', 1),
                                                      (165, 'Midwood', 2),
                                                      (166, 'Morningside Heights', 1),
                                                      (167, 'Morrisania/Melrose', 4),
                                                      (168, 'Mott Haven/Port Morris', 4),
                                                      (169, 'Mount Hope', 4),
                                                      (170, 'Murray Hill', 1),
                                                      (171, 'Murray Hill-Queens', 3),
                                                      (172, 'New Dorp/Midland Beach', 5),
                                                      (173, 'North Corona', 3),
                                                      (174, 'Norwood', 4),
                                                      (175, 'Oakland Gardens', 3),
                                                      (176, 'Oakwood', 5),
                                                      (177, 'Ocean Hill', 2),
                                                      (178, 'Ocean Parkway South', 2),
                                                      (179, 'Old Astoria', 3),
                                                      (180, 'Ozone Park', 3),
                                                      (181, 'Park Slope', 2),
                                                      (182, 'Parkchester', 4),
                                                      (183, 'Pelham Bay', 4),
                                                      (184, 'Pelham Bay Park', 4),
                                                      (185, 'Pelham Parkway', 4),
                                                      (186, 'Penn Station/Madison Sq West', 1),
                                                      (187, 'Port Richmond', 5),
                                                      (188, 'Prospect-Lefferts Gardens', 2),
                                                      (189, 'Prospect Heights', 2),
                                                      (190, 'Prospect Park', 2),
                                                      (191, 'Queens Village', 3),
                                                      (192, 'Queensboro Hill', 3),
                                                      (193, 'Queensbridge/Ravenswood', 3),
                                                      (194, 'Randalls Island', 1),
                                                      (195, 'Red Hook', 2),
                                                      (196, 'Rego Park', 3),
                                                      (197, 'Richmond Hill', 3),
                                                      (198, 'Ridgewood', 3),
                                                      (199, 'Rikers Island', 4),
                                                      (200, 'Riverdale/North Riverdale/Fieldston', 4),
                                                      (201, 'Rockaway Park', 3),
                                                      (202, 'Roosevelt Island', 1),
                                                      (203, 'Rosedale', 3),
                                                      (204, 'Rossville/Woodrow', 5),
                                                      (205, 'Saint Albans', 3),
                                                      (206, 'Saint George/New Brighton', 5),
                                                      (207, 'Saint Nicholas Houses', 1),
                                                      (208, 'Schuylerville/Throgs Neck', 4),
                                                      (209, 'Seaport', 1),
                                                      (210, 'Sheepshead Bay', 2),
                                                      (211, 'SoHo', 1),
                                                      (212, 'Soundview/Bruckner', 4),
                                                      (213, 'Soundview/Castle Hill', 4),
                                                      (214, 'South Beach/Dongan Hills', 5),
                                                      (215, 'South Jamaica', 3),
                                                      (216, 'South Ozone Park', 3),
                                                      (217, 'South Williamsburg', 2),
                                                      (218, 'Springfield Gardens North', 3),
                                                      (219, 'Springfield Gardens South', 3),
                                                      (220, 'Spuyten Duyvil/Kingsbridge', 4),
                                                      (221, 'Stapleton', 5),
                                                      (222, 'Starrett City', 2),
                                                      (223, 'Steinway', 3),
                                                      (224, 'Stuy Town/Peter Cooper Village', 1),
                                                      (225, 'Stuyvesant Heights', 2),
                                                      (226, 'Sunnyside', 3),
                                                      (227, 'Sunset Park East', 2),
                                                      (228, 'Sunset Park West', 2),
                                                      (229, 'Sutton Place/Beekman Place', 1),
                                                      (230, 'Times Square/Theatre District', 1),
                                                      (231, 'TriBeCa/Civic Center', 1),
                                                      (232, 'Two Bridges/Lower East Side', 1),
                                                      (233, 'UN/Turtle Bay South', 1),
                                                      (234, 'Union Square', 1),
                                                      (235, 'University Heights/Morris Heights', 4),
                                                      (236, 'Upper East Side North', 1),
                                                      (237, 'Upper East Side South', 1),
                                                      (238, 'Upper West Side North', 1),
                                                      (239, 'Upper West Side South', 1),
                                                      (240, 'Van Cortlandt Park', 4),
                                                      (241, 'Van Cortlandt Village', 4),
                                                      (242, 'Van Nest/Morris Park', 4),
                                                      (243, 'Washington Heights North', 1),
                                                      (244, 'Washington Heights South', 1),
                                                      (245, 'West Brighton', 5),
                                                      (246, 'West Chelsea/Hudson Yards', 1),
                                                      (247, 'West Concourse', 4),
                                                      (248, 'West Village', 1),
                                                      (249, 'West Village', 1),
                                                      (250, 'Westchester Village/Unionport', 4),
                                                      (251, 'Westerleigh', 5),
                                                      (252, 'Whitestone', 3),
                                                      (253, 'Willets Point', 3),
                                                      (254, 'Williamsbridge/Olinville', 4),
                                                      (255, 'Williamsburg (North Side)', 2),
                                                      (256, 'Williamsburg (South Side)', 2),
                                                      (257, 'Windsor Terrace', 2),
                                                      (258, 'Woodhaven', 3),
                                                      (259, 'Woodlawn/Wakefield', 4),
                                                      (260, 'Woodside', 3),
                                                      (261, 'World Trade Center', 1),
                                                      (262, 'Yorkville East', 1),
                                                      (263, 'Yorkville West', 1),
                                                      (264, 'Unknown', 6),
                                                      (265, 'Unknown', 6);